FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# wind

Wind is an API for WindOJ.

## Problems Collection [/problems]

### List All Problems [GET]

+ Response 200 (application/json)

### Create a New Problem [POST]

+ Request (application/json)

+ Response 201 (application/json)